version: "3"

volumes:
  postgres_volume:

services:
  db:
    build: ./pkg
    restart: always
    container_name: postgres
    volumes:
    - postgres_volume:/var/lib/postgresql/data
    ports:
    - 5432:5432
  main_app:
    build: .
    depends_on:
      - db
    restart: always
    container_name: main-app
    ports:
    - 8000:8000